resource "helm_release" "kube_prometheus_stack" {
  name             = "prometheus"
  repository       = "https://prometheus-community.github.io/helm-charts"
  chart            = "kube-prometheus-stack"
  namespace        = "monitoring"
  create_namespace = true

  set {
    name  = "grafana.adminPassword"
    value = "admin123"
  }

  # Allow Prometheus to scrape services across all namespaces
  set {
    name  = "prometheus.prometheusSpec.serviceMonitorSelectorNilUsesHelmValues"
    value = "false"
  }

  # --- VPN ACCESS CONFIGURATION ---
  # This gives Grafana an internal IP (e.g., 10.0.x.x) reachable via VPN
  set {
    name  = "grafana.service.type"
    value = "LoadBalancer"
  }

  set {
    name  = "grafana.service.annotations.service\\.beta\\.kubernetes\\.io/aws-load-balancer-internal"
    value = "true"
    type  = "string"
  }
}

# Postgres Exporter (To monitor RDS)
resource "helm_release" "postgres_exporter" {
  name       = "postgres-exporter"
  repository = "https://prometheus-community.github.io/helm-charts"
  chart      = "prometheus-postgres-exporter"
  namespace  = "monitoring"

  depends_on = [helm_release.kube_prometheus_stack]

  set {
    name  = "config.datasource.host"
    value = aws_db_instance.vector_db.address
  }

  set {
    name  = "config.datasource.user"
    value = var.db_username
  }

  set {
    name  = "config.datasource.password"
    value = var.db_password
  }

  set {
    name  = "config.datasource.sslmode"
    value = "require"
  }

  set {
    name  = "config.datasource.database"
    value = "vectordb"
  }

  # Enable the ServiceMonitor so Prometheus finds it automatically
  set {
    name  = "serviceMonitor.enabled"
    value = "true"
  }
}

data "kubernetes_service" "grafana" {
  metadata {
    name      = "prometheus-grafana" # The default name generated by the chart
    namespace = "monitoring"
  }

  depends_on = [helm_release.kube_prometheus_stack]
}